[package]
name = "sinfonic-source-jellyfin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Jellyfin MusicProvider implementation (v0.1)"

[dependencies]
sinfonic-domain = { workspace = true }
sinfonic-source = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
